## creating Array

In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([(1,2,3),(4,5,6)]) 

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [8]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [9]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [10]:
np.random.rand(4,5)

array([[0.8060371 , 0.40114589, 0.25843832, 0.67512795, 0.7986406 ],
       [0.70101328, 0.35504517, 0.16534981, 0.65535745, 0.14842421],
       [0.55081798, 0.29850683, 0.2073169 , 0.60958899, 0.97963147],
       [0.89082254, 0.82309612, 0.14755708, 0.85949674, 0.90508432]])

In [11]:
np.random.rand(6,7)*100

array([[61.57864138, 10.15039142,  9.03371586, 47.27330926, 31.02065744,
        85.94495335,  1.7226937 ],
       [14.28904564, 13.64010357, 25.44591687,  0.44054561, 70.87711762,
        96.95672553, 63.55336723],
       [15.03342477, 87.73105881, 31.64804429, 28.6795456 , 74.06242755,
        66.1690275 , 86.71593962],
       [42.10749963, 24.65630233, 72.01668828, 63.81103512, 39.21050381,
        18.5027177 , 42.82069736],
       [70.90169961, 31.59451674, 65.99452313, 24.48377355, 67.7917202 ,
        45.07233877, 12.56811307],
       [46.83622714, 12.99842029, 62.72039519, 18.88408633, 57.45777406,
        25.65180065, 90.20280168]])

In [12]:
np.random.randint(5,size=(2,3)) 

array([[3, 3, 4],
       [2, 3, 4]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
import array as arr

In [20]:
np.array([])

array([], dtype=float64)

In [21]:
np.size

<function numpy.size(a, axis=None)>

In [22]:
np.dtype

numpy.dtype

In [24]:
np.eye

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)>

In [29]:
np.copy

<function numpy.copy(a, order='K', subok=False)>